"""
advisory_api.py

FastAPI route layer for the LLM advisory feature.

This file is intentionally thin.
It should only do four things:
1) define request / response schemas for the advisory endpoint
2) validate the incoming payload
3) call the local LLM service
4) return a clean JSON response

Design note:
- Forecasting logic already lives in the existing /forecast endpoint.
- This endpoint does not recompute PV or ROI.
- It only explains forecast outputs in natural language.

Typical flow:
    frontend -> POST /forecast -> get forecast_result
    frontend -> POST /advisory with {user_question, forecast_result}
    backend  -> local model generates an explanation
"""

from __future__ import annotations

from typing import Any, Dict, Literal

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field, field_validator

from .llm_service import llm_service


RunMode = Literal["mock", "local"]
Language = Literal["en", "zh"]


router = APIRouter(tags=["advisory"])


class AdvisoryRequest(BaseModel):
    """
    Input payload for POST /advisory.

    We keep forecast_result as a generic dict on purpose.
    The structure comes from the existing /forecast endpoint, and we want
    this endpoint to accept that response directly without extra conversion.
    """

    user_question: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="User's natural-language question about the forecast result.",
    )
    forecast_result: Dict[str, Any] = Field(
        ...,
        description="JSON response previously returned by POST /forecast.",
    )
    language: Language = Field(
        default="en",
        description="Answer language: 'en' or 'zh'.",
    )
    run_mode: RunMode = Field(
        default="local",
        description="Generation mode: 'mock' for rule-based fallback, 'local' for local model inference.",
    )
    max_new_tokens: int = Field(
        default=220,
        ge=50,
        le=600,
        description="Maximum number of new tokens generated by the local model.",
    )
    temperature: float = Field(
        default=0.3,
        ge=0.0,
        le=1.5,
        description="Sampling temperature. Lower is usually more stable.",
    )
    top_p: float = Field(
        default=0.9,
        gt=0.0,
        le=1.0,
        description="Top-p nucleus sampling parameter.",
    )

    @field_validator("user_question")
    @classmethod
    def strip_and_check_question(cls, value: str) -> str:
        """
        Remove accidental leading/trailing whitespace.

        We also reject questions that become empty after stripping, because that
        usually means the frontend sent a blank input by mistake.
        """
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("user_question cannot be empty.")
        return cleaned

    @field_validator("forecast_result")
    @classmethod
    def check_forecast_result_shape(cls, value: Dict[str, Any]) -> Dict[str, Any]:
        """
        Do a lightweight structure check.

        We do not validate every nested field here, because the forecasting
        endpoint may evolve a bit. Still, it is useful to make sure the payload
        looks like a forecast response rather than an unrelated JSON object.
        """
        expected_top_keys = {"location", "inputs_used", "pv_kwh", "roi"}


        missing = [k for k in expected_top_keys if k not in value]
        if missing:
            raise ValueError(
                "forecast_result does not look like a valid /forecast response. "
                f"Missing keys: {missing}"
            )
        return value


class AdvisoryResponse(BaseModel):
    """
    Output payload returned by POST /advisory.
    """

    answer: str = Field(..., description="Natural-language advisory answer.")
    disclaimer: str = Field(..., description="Short disclaimer shown to the user.")
    used_model: str = Field(..., description="Model path or model label used to generate the answer.")
    run_mode: str = Field(..., description="Actual generation mode used by the service.")
    status: str = Field(default="success", description="Request status.")


@router.get("/advisory/health", summary="Liveness check for advisory module")
def advisory_health() -> dict:
    """
    Small health endpoint for the advisory module.

    This is handy during deployment because it lets us confirm the route is
    registered before we test the full generation path.
    """
    return {"status": "ok", "module": "advisory"}


@router.post("/advisory", response_model=AdvisoryResponse, summary="Generate advisory answer from forecast output")
def advisory(req: AdvisoryRequest) -> AdvisoryResponse:
    """
    Generate a natural-language explanation for a forecast result.

    Expected usage:
    1) Call /forecast first
    2) Send the returned JSON here together with the user's question
    3) Receive an advisory answer written by the local LLM service
    """
    try:
        result = llm_service.generate_advisory(
            user_question=req.user_question,
            forecast_result=req.forecast_result,
            language=req.language,
            run_mode=req.run_mode,
            max_new_tokens=req.max_new_tokens,
            temperature=req.temperature,
            top_p=req.top_p,
        )

        return AdvisoryResponse(
            answer=result.answer,
            disclaimer=result.disclaimer,
            used_model=result.used_model,
            run_mode=result.run_mode,
            status=result.status,
        )

    except FileNotFoundError as exc:
        # This is the most common deployment mistake:
        # the API is up, but the local model has not been downloaded yet.
        raise HTTPException(
            status_code=500,
            detail=(
                "Local model files were not found. "
                "Please run download_model.py first or check LOCAL_LLM_MODEL_PATH."
            ),
        ) from exc

    except ValueError as exc:
        # Use 400 when the payload is structurally valid JSON but semantically wrong.
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    except Exception as exc:
        # Keep the fallback message simple.
        # Detailed logs can still be inspected on the server side.
        raise HTTPException(
            status_code=500,
            detail=f"Advisory generation failed: {str(exc)}",
        ) from exc
